[build]
  base = "/"
  publish = ".next"
  command = "npm run build"
  functions = "/netlify"

[build.environment]
  NEXT_SERVERLESS = "true"
  SANITY_PROJECT_ID="2li0t47r"
  SANITY_DATASET="production"
  BUILD_LANGUAGES = "en-US,it-IT"
  BUILD_CMS = "sanity"
  CL_CLIENT_ID = "ylA23OoZIrwixpsl0yKsDgcGhqoGWiZJSyRBoOWjSLc"
  CL_ENDPOINT = "https://henry-netlify.commercelayer.io"
